# Site settings
title: Ketan Bhatt
email: ketanbhatt1006@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A diary of sorts for all that I like about web development, and a journal
  that covers my experiments, failed or successful. Looking forward to
  interact with the community, let's have a good time!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: theketanbhatt
github_username:  ketanbhatt

# Build settings
markdown: kramdown
