# Site settings
title: Ketan Bhatt
email: ketanbhatt1006@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Space where I put my learnings in the tech field
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ketanbhatt.github.io" # the base hostname & protocol for your site
twitter_username: ktnbhtt
github_username:  ketanbhatt
author: ketanbhatt

# Build settings
markdown: kramdown

permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
theme: jekyll-theme-modernist